### ISSUE TITLE
Add metadata collection

### ISSUE THREAD

**Issue by ErikGartner** [ErikGartner/stock-collector#5]
We want a second collection that tracks the data downloaded for each instrument.

That is we want to:

- Be able to quickly detect any missing intervals due to unforeseen downtime.
- Quickly determine what data we have for each stock.

This should be stored in a second metadata collection that tracks what intervals we have for each instrument. This collection is updated each time the collector fetches new data.

**Comment by johanmodin** [comment]
Added in commit e49a9c720cb2a35b254c3cbb56797c9b75ceedc5
